name: Short Form Video Request
description: Request a short form video about a feature
title: "[Request For Short Form Video] <title>"
labels: [Short Form Video]
body:
- type: input
  attributes:
    label: Feature Name
    description: Which feature is this video for?
    placeholder: ex. Codespaces
  validations:
    required: true
- type: textarea
  attributes:
    label: Product Owner
    description: Who is the product owner of this feature?
    placeholder: ex. @handle
  validations:
    required: true
- type: dropdown
  attributes:
    label: Platform
    description: Where should this video be posted?
    multiple: true
    options:
      - Youtube
      - Linkedin
      - Twitter
      - TikTok
      - Other
  validations:
    required: true
- type: textarea
  attributes:
    label: More Information
    description: If you would like to add any more information, please add it below
    placeholder: You rock!
  validations:
    required: false
