name: Short Form Video Request
description: Request a short form video about a feature
title: "[Request For Short Form Video] <title>"
labels: [Short Form Video]
body:
- type: input
  attributes:
    label: Feature Name
    description: Which feature is this video for?
    placeholder: ex. Codespaces
  validations:
    required: true
- type: textarea
  attributes:
    label: Product Owner
    description: Who is the product owner of this feature?
    placeholder: ex. @handle
  validations:
    required: true
